name: sello_store_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  http: ^1.2.2
  font_awesome_flutter: ^10.7.0
  modal_progress_hud_nsn: ^0.5.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"  # Logo image path
  min_sdk_android: 21

  flutter_lints: ^3.0.0


flutter_native_splash:
  color: "#CCE3DE"   # Color of the background of the splash screen 
  image: assets/images/icon.png  # image path
  android_12:
    image: assets/images/icon.png  # image path
    color: "#CCE3DE"   # Color of the background of the splash screen 

flutter:


  uses-material-design: true

  assets:
    - assets/images/




  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
